---
- name: "Download kubectl"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
# - name: "Download kubectl"
#   shell: curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl"
#   args:
#     chdir: "{{ ansible_env.HOME }}"
#   environment:
#     HOME: "{{ ansible_env.HOME }}"

# - name: "Apply execute permissions to the binary"
#   shell: chmod +x "{{ ansible_env.HOME }}/kubectl"

# - name: "Copy the binary to a folder in $PATH"
#   shell: mkdir -p "{{ ansible_env.HOME }}/bin" && mv "{{ ansible_env.HOME }}/kubectl" "{{ ansible_env.HOME }}/bin/kubectl"
#   environment:
#     HOME: "{{ ansible_env.HOME }}"

# - name: "Add the $HOME/bin path to the shell initialization file"
#   lineinfile:
#     line: 'export PATH=$PATH:{{ ansible_env.HOME }}/bin'
#     dest: "{{ ansible_env.HOME }}/.bashrc"
#     create: yes

# - name: "Update current shell PATH"
#   shell: export PATH=$PATH:{{ ansible_env.HOME }}/bin