Description: Creates two individual hosts to manage the EKS-Cluster

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  KeyPairName:
    Description: SSH key for management access
    Default: udacity
    Type: AWS::EC2::KeyPair::KeyName
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0261755bbcb8c4a84
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Security group for the nodes 
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPC" 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1025
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1025
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      

  managementHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyPairName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management1
        - Key: Project
          Value: !Ref EnvironmentName

  managementHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyPairName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management2
        - Key: Project
          Value: !Ref EnvironmentName
