apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: capstoneproject
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
        - image: tuannns99/capstoneproject:latest
          imagePullPolicy: Always
          name: capstoneproject
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
spec:
  type: LoadBalancer
  selector:
    app: capstoneproject
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP