apiVersion: v1
kind: Service
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
spec:
  type: LoadBalancer
  selector:
    app: capstoneproject
  ports:
    - port: 80
      targetPort: 80